library(tidyverse)
library(FactoMineR)
df <- readRDS("data/master/ess_final.rds")
active_vars <- c("freehms_r", "gincdif_r", "imbgeco_3cat", "imueclt_3cat", "imwbcnt_3cat")
cd <- df %>% filter(cntry == "PT") %>% filter(if_all(all_of(active_vars), ~ !is.na(.)))
mca_data <- cd %>% mutate(across(all_of(active_vars), factor), essround = factor(essround))
mca_input <- mca_data %>% select(all_of(active_vars), essround)
res <- MCA(mca_input, quali.sup = which(names(mca_input) == "essround"), ncp = 5, graph = FALSE)
hc <- HCPC(res, nb.clust = -1, consol = TRUE, graph = FALSE)
cat("Column names in data.clust:\n")
cat(names(hc$data.clust), sep = "\n")
cat("\n\nFirst few rows:\n")
print(head(hc$data.clust[, c(1:3, ncol(hc$data.clust))]))
